services:
  mysql:
    build: .
    container_name: mi_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: primac
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - primac

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
      
volumes:
  db_data:

networks:
  primac:
    external: true
